# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
inhibit_all_warnings!

target 'swiftChatter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftChatter
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'GoogleSignIn'
  pod 'MessageKit'
  pod 'SwiftLint'

end


post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end


